---
# tasks file for ansible-role-asterisk-config-deploy

- name: Install requirements via apt
  apt: name={{item}} state=present
  with_items:
  - git

- name: Create directory for asterisk config files
  file: path={{ asterisk_config_deploy_repo_directory }} state=directory mode=755

- name: Git checkout from git repo
  git: repo={{ asterisk_config_deploy_repo }}
       dest={{ asterisk_config_deploy_repo_directory }}
  notify: 
  - asterisk find repo subfolder files
  - asterisk symlink repo subfolder files
  - asterisk find repo override files
  - asterisk symlink repo override files
