---
# tasks file for ansible-role-asterisk-config-deploy

- name: Install requirements via apt
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - git
    - git-lfs
  register: my_result
  until: my_result is succeeded
  tags: asterisk-config-deploy

# Permissions set to 0777 so that they can be accessed by the user running git
- name: Create directory for asterisk config files
  file:
    path: "{{ asterisk_config_deploy_path }}"
    state: directory
    mode: 0777
  tags: asterisk-config-deploy

# This task runs 'become: no' to install for the relevant user instead of root
- name: Ensure Git LFS is installed
  shell: >
    cat ~/.gitconfig | grep -q 'git-lfs'
    && echo -n 'INSTALLED'
    || git lfs install
  become: no
  register: git_lfs_result
  changed_when: git_lfs_result.stdout != 'INSTALLED'
  tags: asterisk-config-deploy
  
# This task runs 'become: no' so that the user's SSH keys can be used to connect to the git repo
- name: Git checkout from git repo
  git:
    repo: "{{ asterisk_config_deploy_repo }}"
    dest: "{{ asterisk_config_deploy_path }}"
    version: master
  become: no
  notify: 
  - asterisk find repo base files
  - asterisk symlink repo base files
  - asterisk find repo override files
  - asterisk symlink repo override files
  - asterisk reload
  tags: asterisk-config-deploy
  
- name: Check repo sounds directory
  stat:
    path: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_sounds_dir }}"
  register: sounds_dir
  tags: asterisk-config-deploy
  
- name: Symlink repo sounds directory
  file:
    src: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_sounds_dir }}"
    dest: "{{ asterisk_config_deploy_sounds_path }}"
    state: link
    force: yes
  when: sounds_dir.stat.isdir is defined and sounds_dir.stat.isdir
  tags: asterisk-config-deploy

- name: Check repo moh directory
  stat:
    path: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_moh_dir }}"
  register: moh_dir
  tags: asterisk-config-deploy

- name: Symlink repo moh directory
  file:
    src: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_moh_dir }}"
    dest: "{{ asterisk_config_deploy_moh_path }}"
    state: link
    force: yes
  when: moh_dir.stat.isdir is defined and moh_dir.stat.isdir
  tags: asterisk-config-deploy
  