---
# tasks file for ansible-role-asterisk-config-deploy

- name: Install requirements via apt
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - git
    - git-lfs
  register: my_result
  until: my_result is succeeded
  tags: asterisk-config-deploy

# Permissions set to 0777 so that they can be accessed by the user running git
- name: Create directory for asterisk config files
  file:
    path: "{{ asterisk_config_deploy_path }}"
    state: directory
    mode: 0777
  tags: asterisk-config-deploy

- name: Ensure user has a .gitconfig file
  file:
    

- name: Ensure Git LFS is installed
  shell: >
    cat ~/.gitconfig | grep -q 'git-lfs'
    && echo -n 'INSTALLED'
    || git lfs install
  register: git_lfs_result
  changed_when: git_lfs_result.stdout != 'INSTALLED'
  tags: asterisk-config-deploy

# This task runs 'become: no' so that the users SSH keys can be used to connect to the git repo
- name: Git checkout from git repo
  git:
    repo: "{{ asterisk_config_deploy_repo }}"
    dest: "{{ asterisk_config_deploy_path }}"
    version: master
  become: no
  notify: 
  - asterisk find repo base files
  - asterisk symlink repo base files
  - asterisk find repo override files
  - asterisk symlink repo override files
  - asterisk check repo sounds directory
  - asterisk symlink repo sounds directory
  - asterisk check repo moh directory
  - asterisk symlink repo moh directory
  - asterisk reload
  tags: asterisk-config-deploy
