---
# tasks file for ansible-role-asterisk-config-deploy

- name: Install requirements via apt
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - git
    - git-lfs
  register: my_result
  until: my_result is succeeded
  tags: asterisk-config-deploy

# Runs as current user, not root
# Set permissions so current user and group can write
# Other users can only read the files (ie. asterisk user)
- name: Create directory for asterisk config files
  file:
    path: "{{ asterisk_config_deploy_path }}"
    state: directory
    mode: u+rwx,g+rwx,o=rx
  become: no
  tags: asterisk-config-deploy

# This task runs 'become: no' to install for the current user instead of root
- name: Ensure Git LFS is installed
  shell: >
    cat ~/.gitconfig | grep -q 'git-lfs'
    && echo -n 'INSTALLED'
    || git lfs install
  become: no
  register: git_lfs_result
  changed_when: git_lfs_result.stdout != 'INSTALLED'
  tags: asterisk-config-deploy
  
# This task runs 'become: no' so that the current user's SSH key is used to connect to the git repo
- name: Git checkout from git repo
  git:
    repo: "{{ asterisk_config_deploy_repo }}"
    dest: "{{ asterisk_config_deploy_path }}"
    version: master
  become: no
  notify: 
  - asterisk find repo base files
  - asterisk symlink repo base files
  - asterisk find repo override files
  - asterisk symlink repo override files
  - asterisk reload
  tags: asterisk-config-deploy
  
- name: Reinitialize git repo with access for group
  shell: >
    cat .git/config | grep -q 'sharedrepository = 1'
    && echo -n 'SHARED'
    || git init --shared=group
  args:
    chdir: "{{ asterisk_config_deploy_path }}"
  become: no
  register: git_shared_result
  changed_when: git_shared_result.stdout != 'SHARED'
  when: asterisk_config_deploy_group != ''
  notify: git set group permissions
  tags: asterisk-config-deploy

- name: Check repo sounds directory
  stat:
    path: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_sounds_dir }}"
  register: sounds_dir
  tags: asterisk-config-deploy
  
- name: Symlink repo sounds directory
  file:
    src: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_sounds_dir }}"
    dest: "{{ asterisk_config_deploy_sounds_path }}"
    state: link
    force: yes
  when: sounds_dir.stat.isdir is defined and sounds_dir.stat.isdir
  tags: asterisk-config-deploy

- name: Check repo moh directory
  stat:
    path: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_moh_dir }}"
  register: moh_dir
  tags: asterisk-config-deploy

- name: Symlink repo moh directory
  file:
    src: "{{ asterisk_config_deploy_path }}{{ asterisk_config_deploy_moh_dir }}"
    dest: "{{ asterisk_config_deploy_moh_path }}"
    state: link
    force: yes
  when: moh_dir.stat.isdir is defined and moh_dir.stat.isdir
  tags: asterisk-config-deploy
  