---
# handlers file for ansible-role-asterisk-config-deploy

- name: asterisk find repo config files
  find:
    paths: "{{ asterisk_config_deploy_repo_directory }}{{ asterisk_config_deploy_repo_subfolder }}"
    patterns: "*.conf,*.ael,*.adsi,*.lua"
  register: find

- name: asterisk symlink repo config files
  file:
    src: "{{ asterisk_config_deploy_repo_directory }}{{ asterisk_config_deploy_repo_subfolder }}{{ item.path | basename }}"
    dest: "{{ asterisk_config_deploy_asterisk_directory }}{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find.files }}"
  notify: asterisk reload
  
- name: asterisk reload
  service: name=asterisk state=restarted
