---
# handlers file for ansible-role-asterisk-config-deploy

- name: asterisk find repo subfolder files
  find:
    paths: "{{ asterisk_config_deploy_repo_directory }}{{ asterisk_config_deploy_repo_subfolder }}"
    patterns: "*.conf,*.ael,*.adsi,*.lua"
  register: find_subfolder

- name: asterisk symlink repo subfolder files
  file:
    src: "{{ asterisk_config_deploy_repo_directory }}{{ asterisk_config_deploy_repo_subfolder }}{{ item.path | basename }}"
    dest: "{{ asterisk_config_deploy_asterisk_directory }}{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find_subfolder.files }}"
  notify: asterisk reload

- name: asterisk find repo override files
  find:
    paths: "{{ asterisk_config_deploy_repo_directory }}{{ asterisk_config_deploy_repo_override_subfolder }}"
    patterns: "*.conf,*.ael,*.adsi,*.lua"
  register: find_override

- name: asterisk symlink repo override files
  file:
    src: "{{ asterisk_config_deploy_repo_directory }}{{ asterisk_config_deploy_repo_override_subfolder }}{{ item.path | basename }}"
    dest: "{{ asterisk_config_deploy_asterisk_directory }}{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find_override.files }}"
  notify: asterisk reload
  
- name: asterisk reload
  service: name=asterisk state=restarted
