---
# handlers file for ansible-role-asterisk-config-deploy

- name: asterisk find repo base files
  find:
    paths: "{{ asterisk_config_deploy_base_path }}"
    patterns: "*.conf,*.ael,*.adsi,*.lua,*.sh"
  register: find_base

- name: asterisk symlink repo base files
  file:
    src: "{{ asterisk_config_deploy_base_path }}{{ item.path | basename }}"
    dest: "{{ asterisk_config_deploy_asterisk_path }}{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find_base.files }}"
  notify: asterisk reload

- name: asterisk find repo override files
  find:
    paths: "{{ asterisk_config_deploy_or_path }}"
    patterns: "*.conf,*.ael,*.adsi,*.lua,*.sh"
  register: find_override

- name: asterisk symlink repo override files
  file:
    src: "{{ asterisk_config_deploy_or_path }}{{ item.path | basename }}"
    dest: "{{ asterisk_config_deploy_asterisk_path }}{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ find_override.files }}"
  notify: asterisk reload

- name: asterisk reload
  service: name=asterisk state=reloaded

- name: git set group permissions
  file:
    path: "{{ asterisk_config_deploy_path }}"
    state: directory
    recurse: yes
    group: "{{ asterisk_config_deploy_group }}"
    mode: g+swX
  when: asterisk_config_deploy_group != ""
