---
# handlers file for ansible-role-asterisk-config-deploy

- name: asterisk symlink config files
  file:
    src: "{{ asterisk-config-deploy-repo-directory }}{{ item }}"
    dest: "{{ asterik-config-deploy-asterisk-directory }}{{ item }}"
    state: link
    force: yes
  with_items:
    - extensions.conf
    - voicemail.conf
  notify: asterisk reload
  
- name: asterisk reload
  service: name=asterisk state=restarted
